### ISSUE TITLE
Need Implementation of Queue and all its operations in c++

### ISSUE THREAD

**Issue by Manraj-Mann** [Manraj-Mann/Hacktoberfest-DSA-Codes#3]
- [x]  Insertion in a queue
- [x] Deletion in a queue
- [x] Double ended queue
- [x] Circular Queue

**Comment by shivam-bhadani** [comment]
Please assign me this issue I will work on it

**Comment by pratiksrivastava01** [comment]
@Manraj-Mann can i work on this

**Comment by pratiksrivastava01** [comment]
@Manraj-Mann assign this to me

**Comment by Manraj-Mann** [comment]
okay sure but please add comments in codes too

**Comment by pratiksrivastava01** [comment]
Ok sure

**Comment by shivam-bhadani** [comment]
Ok will add comments also

**Comment by shivam-bhadani** [comment]
Made pull request please merge it

**Comment by satrio-pamungkas** [comment]
@Manraj-Mann Hello, Am I allow to contribute outside issues listing ?

I'm referring to list of language in **README.md** and list of DSA implementation in **CONTRIBUTING.md**

**Comment by Manraj-Mann** [comment]
> @Manraj-Mann Hello, Am I allow to contribute outside issues listing ?
> 
> I'm referring to list of language in **README.md** and list of DSA implementation in **CONTRIBUTING.md**

yes , you can

**Comment by Faizan96322** [comment]
hey, I would like to contribute to this issue, pls assign me this task!
I would work on deletion of the queue in c, cpp and python!

**Comment by abhayanand08** [comment]
@Manraj-Mann can u assign me the last task that is of deletion in a queue. I would love contributing to your repository. Kindly assign me this task.

**Comment by Manraj-Mann** [comment]
> @Manraj-Mann can u assign me the last task that is of deletion in a queue. I would love contributing to your repository. Kindly assign me this task.

Yes Assigning

**Comment by Manraj-Mann** [comment]
> hey, I would like to contribute to this issue, pls assign me this task! I would work on deletion of the queue in c, cpp and python!

Ok

**Comment by coolwednesday** [comment]
hey, I would like to contribute to this issue, can you please assign me this task ?

**Comment by Manraj-Mann** [comment]
> hey, I would like to contribute to this issue, can you please assign me this task ?

**Comment by Manraj-Mann** [comment]
> hey, I would like to contribute to this issue, can you please assign me this task ?

Sorry its already completed , you can try contributing to some other issue or refer to contributing.md file
